'use client'

import { motion } from 'framer-motion'
import { useEffect, useState } from 'react'
import { revealItem } from '@/components/motion/presets'
import { Headline } from '@/components/shared/Headline'
import { SectionWrapper } from '@/components/shared/SectionWrapper'
import { ApplicationNode } from './ApplicationNode'
import { ArchitectureExplanation } from './ArchitectureExplanation'
import { BackendNode } from './BackendNode'
import { Connector, ConnectorFan } from './Connector'
import { DatabaseNode } from './DatabaseNode'

type ApplicationId = 'client' | 'employee' | 'management' | 'website'
type Target = ApplicationId | 'finale'
type PulseStage = 'backend' | 'card' | 'database' | 'fade' | 'hold' | 'toBackend' | 'toDatabase'

type Application = {
  description: string
  icon: ApplicationId
  id: ApplicationId
  label: string
}

const applications: readonly Application[] = [
  {
    id: 'website',
    icon: 'website',
    label: 'Website',
    description:
      'Customers create bookings through the website, but the backend validates business rules, stores operational data, and initiates the workflow.',
  },
  {
    id: 'management',
    icon: 'management',
    label: 'Management Workspace',
    description:
      'Managers coordinate operations through the backend, which maintains scheduling, assignments, finance, and reporting.',
  },
  {
    id: 'employee',
    icon: 'employee',
    label: 'Employee Workspace',
    description:
      'Employees interact with assigned work while the backend controls workflow transitions and records operational activity.',
  },
  {
    id: 'client',
    icon: 'client',
    label: 'Client Portal',
    description:
      'Clients access information generated by the backend without duplicating operational logic.',
  },
]

const FINALE = {
  title: 'One Shared System',
  description:
    'Every interface — website, management, employee, and client — depends on the same operational core through the enterprise backend.',
}

const AUTOPLAY_STEP_MS = 2400
const FINALE_TOTAL_MS = 3800

const REGULAR_SEQUENCE: readonly { at: number; stage: PulseStage }[] = [
  { stage: 'card', at: 0 },
  { stage: 'toBackend', at: 150 },
  { stage: 'backend', at: 600 },
  { stage: 'toDatabase', at: 1200 },
  { stage: 'database', at: 1600 },
  { stage: 'fade', at: 1950 },
]

// The "all connected" finale: every connector activates, the backend reaches
// its brightest state with one slow heartbeat, a wave of light continues down
// to the database, the database responds, and the whole diagram holds in a
// softly illuminated "connected" state for about a second before fading.
const FINALE_SEQUENCE: readonly { at: number; stage: PulseStage }[] = [
  { stage: 'card', at: 0 },
  { stage: 'toBackend', at: 150 },
  { stage: 'backend', at: 650 },
  { stage: 'toDatabase', at: 1450 },
  { stage: 'database', at: 1900 },
  { stage: 'hold', at: 2300 },
  { stage: 'fade', at: 3300 },
]

function AppIcon({ id }: { id: ApplicationId }) {
  const common = {
    'aria-hidden': true,
    className: 'size-5',
    fill: 'none',
    stroke: 'currentColor',
    strokeLinecap: 'round' as const,
    strokeLinejoin: 'round' as const,
    strokeWidth: 1.75,
    viewBox: '0 0 24 24',
  }

  if (id === 'website') {
    return (
      <svg {...common}>
        <circle cx="12" cy="12" r="8.5" />
        <path d="M3.5 12h17M12 3.5c2.5 2.5 3.8 5.5 3.8 8.5s-1.3 6-3.8 8.5c-2.5-2.5-3.8-5.5-3.8-8.5S9.5 6 12 3.5Z" />
      </svg>
    )
  }

  if (id === 'management') {
    return (
      <svg {...common}>
        <rect x="3" y="4" width="8" height="7" rx="1.5" />
        <rect x="13" y="4" width="8" height="7" rx="1.5" />
        <rect x="3" y="13" width="8" height="7" rx="1.5" />
        <rect x="13" y="13" width="8" height="7" rx="1.5" />
      </svg>
    )
  }

  if (id === 'employee') {
    return (
      <svg {...common}>
        <rect x="4" y="3" width="16" height="18" rx="2" />
        <circle cx="12" cy="9.5" r="2.4" />
        <path d="M8 17c0-2.2 1.8-3.5 4-3.5s4 1.3 4 3.5" />
      </svg>
    )
  }

  return (
    <svg {...common}>
      <path d="M12 3l7 3v6c0 5-3.5 7.5-7 9-3.5-1.5-7-4-7-9V6l7-3Z" />
      <circle cx="12" cy="10.3" r="2.1" />
      <path d="M9 15c0-1.8 1.3-2.8 3-2.8s3 1 3 2.8" />
    </svg>
  )
}

export function BackendArchitectureHero() {
  const [selected, setSelected] = useState<ApplicationId | null>(null)
  const [clickToken, setClickToken] = useState(0)
  const [autoStep, setAutoStep] = useState(0)
  const [stage, setStage] = useState<PulseStage>('card')
  const [prefersReducedMotion, setPrefersReducedMotion] = useState(false)

  useEffect(() => {
    const query = window.matchMedia('(prefers-reduced-motion: reduce)')
    setPrefersReducedMotion(query.matches)
    const handleChange = () => setPrefersReducedMotion(query.matches)
    query.addEventListener('change', handleChange)
    return () => query.removeEventListener('change', handleChange)
  }, [])

  useEffect(() => {
    if (selected || prefersReducedMotion) return undefined

    // The finale runs its own longer sequence (wave to database + a hold), so
    // it gets more time in the loop than a single-application step.
    const isCurrentlyFinale = autoStep === applications.length
    const delay = isCurrentlyFinale ? FINALE_TOTAL_MS : AUTOPLAY_STEP_MS

    const timer = window.setTimeout(() => {
      setAutoStep((current) => (current + 1) % (applications.length + 1))
    }, delay)

    return () => window.clearTimeout(timer)
  }, [autoStep, selected, prefersReducedMotion])

  const target: Target = selected ?? (autoStep < applications.length ? applications[autoStep].id : 'finale')
  const isFinale = target === 'finale'

  useEffect(() => {
    if (prefersReducedMotion) {
      setStage(selected ? 'database' : 'card')
      return undefined
    }

    const sequence = isFinale ? FINALE_SEQUENCE : REGULAR_SEQUENCE
    const steps = selected ? sequence.filter((step) => step.stage !== 'fade') : sequence
    const timers = steps.map((step) => window.setTimeout(() => setStage(step.stage), step.at))

    return () => {
      timers.forEach((timer) => window.clearTimeout(timer))
    }
    // target already encodes selected + autoStep; clickToken forces replay on re-selecting the same card.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [target, clickToken, selected, prefersReducedMotion, isFinale])

  const targetIndex = isFinale ? -1 : applications.findIndex((app) => app.id === target)
  const isResting = stage === 'fade'

  const cardActive = applications.map((_, index) =>
    isFinale ? !isResting : index === targetIndex && !isResting,
  )

  const fanPulsing = applications.map((_, index) => {
    const matches = isFinale || index === targetIndex
    return matches && stage === 'toBackend'
  })

  const isConnectedWindow =
    stage === 'toBackend' || stage === 'backend' || stage === 'toDatabase' || stage === 'database' || stage === 'hold'

  const fanActive = applications.map((_, index) => {
    const matches = isFinale || index === targetIndex
    return matches && isConnectedWindow
  })

  const backendPulsing = stage === 'backend'
  const backendGlowing = isConnectedWindow
  const isPeak = isFinale && isConnectedWindow
  const dbConnectorPulsing = stage === 'toDatabase'
  const dbConnectorActive = stage === 'toDatabase' || stage === 'database' || stage === 'hold'
  const databasePulsing = stage === 'database'
  const databaseGlowing = stage === 'database' || stage === 'hold'

  const activeApp = isFinale ? null : applications[targetIndex]

  return (
    <SectionWrapper
      as="section"
      className="border-b border-line bg-canvas py-[var(--space-section)]"
      id="backend-is-the-platform"
    >
      <motion.div
        animate="visible"
        initial="hidden"
        variants={revealItem}
        viewport={{ once: true, amount: 0.3 }}
        whileInView="visible"
      >
        <Headline as="h1" eyebrow="ENGINEERING" size="display">
          Enterprise Backend Architecture
        </Headline>

        <p className="mt-6 max-w-3xl text-body-lg text-pretty text-muted">
          Designing the operational core of a business platform—from domain modelling and
          database architecture to APIs, workflows, and business rules.
        </p>

        <div className="mt-10 max-w-[720px] space-y-5 text-base leading-relaxed text-pretty text-ink sm:text-lg">
          <p>
            Every application is only an interface. The backend is where business rules,
            workflows, permissions, and operational data are managed. It acts as the
            authoritative core of the platform, ensuring that every user works from the same
            operational reality.
          </p>
          <p>
            Whether a booking is created through the website, assigned in the management
            workspace, or completed in the employee app, the backend coordinates every decision
            through one shared system.
          </p>
        </div>
      </motion.div>

      <motion.div
        animate="visible"
        className="mt-14 grid gap-8 lg:grid-cols-[1.35fr_1fr] lg:items-start sm:mt-16"
        initial="hidden"
        variants={revealItem}
        viewport={{ once: true, amount: 0.2 }}
        whileInView="visible"
      >
        <div className="rounded-panel border border-line bg-surface p-5 shadow-card sm:p-8">
          <h2 className="sr-only">Interactive backend architecture diagram</h2>

          <div
            aria-label="Choose an application interface"
            className="grid grid-cols-2 gap-2.5 sm:grid-cols-4 sm:gap-3"
            role="group"
          >
            {applications.map((app, index) => (
              <ApplicationNode
                icon={<AppIcon id={app.icon} />}
                isActive={cardActive[index]}
                key={app.id}
                label={app.label}
                onSelect={() => {
                  setSelected(app.id)
                  setClickToken((current) => current + 1)
                }}
              />
            ))}
          </div>

          <ConnectorFan activeFlags={fanActive} pulsingFlags={fanPulsing} />

          <BackendNode isGlowing={backendGlowing} isPeak={isPeak} isPulsing={backendPulsing} />

          <Connector active={dbConnectorActive} height={36} isPulsing={dbConnectorPulsing} />

          <DatabaseNode isGlowing={databaseGlowing} isPulsing={databasePulsing} />
        </div>

        <ArchitectureExplanation
          description={activeApp ? activeApp.description : FINALE.description}
          eyebrow={isFinale ? 'All interfaces' : 'Selected interface'}
          title={activeApp ? activeApp.label : FINALE.title}
        />
      </motion.div>
    </SectionWrapper>
  )
}
