'use client'

import { motion } from 'framer-motion'
import { useState } from 'react'
import { revealItem } from '@/components/motion/presets'
import { Headline } from '@/components/shared/Headline'
import { SectionWrapper } from '@/components/shared/SectionWrapper'
import { ApplicationNode } from './ApplicationNode'
import { ArchitectureExplanation } from './ArchitectureExplanation'
import { Connector, ConnectorFan } from './Connector'

type ApplicationId = 'client' | 'employee' | 'management' | 'website'

type Application = {
  description: string
  icon: ApplicationId
  id: ApplicationId
  label: string
}

const applications: readonly Application[] = [
  {
    id: 'website',
    icon: 'website',
    label: 'Website',
    description:
      'Customers create bookings through the website, but the backend validates business rules, stores operational data, and initiates the workflow.',
  },
  {
    id: 'management',
    icon: 'management',
    label: 'Management Workspace',
    description:
      'Managers coordinate operations through the backend, which maintains scheduling, assignments, finance, and reporting.',
  },
  {
    id: 'employee',
    icon: 'employee',
    label: 'Employee Workspace',
    description:
      'Employees interact with assigned work while the backend controls workflow transitions and records operational activity.',
  },
  {
    id: 'client',
    icon: 'client',
    label: 'Client Portal',
    description:
      'Clients access information generated by the backend without duplicating operational logic.',
  },
]

const CROSS_CUTTING_CONCERNS = ['Authentication', 'Authorization', 'Validation', 'Tenant Isolation']

type LayerId = 'api' | 'application' | 'database' | 'persistence'

type Layer = {
  detail: string
  explanation: string
  id: LayerId
  label: string
}

const RIBBONED_LAYERS: readonly Layer[] = [
  {
    id: 'api',
    label: 'API Layer',
    detail: 'REST API • Routes • Controllers',
    explanation:
      'The HTTP boundary — 82 endpoints across 16 route groups. Every request is authenticated, authorized, and validated with Zod before it reaches any business logic, and controllers stay thin: they parse, validate, and delegate, never containing business rules themselves.',
  },
  {
    id: 'application',
    label: 'Application Layer',
    detail: 'Business services • Transactions • Business rules',
    explanation:
      'Where business rules actually live. 24 service files make up roughly three-quarters of the entire codebase — every operation that changes state, from creating a booking to finalising payroll, is coordinated here, often inside a transaction.',
  },
  {
    id: 'persistence',
    label: 'Persistence Layer',
    detail: 'Prisma ORM • Query execution',
    explanation:
      'A single Prisma client, extended so that every query is automatically scoped to the current tenant through an AsyncLocalStorage context. Multi-tenancy is enforced structurally here, not left to each service to remember.',
  },
]

const DATABASE_LAYER: Layer = {
  id: 'database',
  label: 'PostgreSQL',
  detail: 'Relational model • Indexes',
  explanation:
    '37 models, 17 enums, and 144 indexes tuned for a tenant-first access pattern. There are no triggers, no stored procedures, and no views — every rule that touches the data lives above this layer, in code.',
}

const ALL_LAYERS: readonly Layer[] = [...RIBBONED_LAYERS, DATABASE_LAYER]

function AppIcon({ id }: { id: ApplicationId }) {
  const common = {
    'aria-hidden': true,
    className: 'size-5',
    fill: 'none',
    stroke: 'currentColor',
    strokeLinecap: 'round' as const,
    strokeLinejoin: 'round' as const,
    strokeWidth: 1.75,
    viewBox: '0 0 24 24',
  }

  if (id === 'website') {
    return (
      <svg {...common}>
        <circle cx="12" cy="12" r="8.5" />
        <path d="M3.5 12h17M12 3.5c2.5 2.5 3.8 5.5 3.8 8.5s-1.3 6-3.8 8.5c-2.5-2.5-3.8-5.5-3.8-8.5S9.5 6 12 3.5Z" />
      </svg>
    )
  }

  if (id === 'management') {
    return (
      <svg {...common}>
        <rect x="3" y="4" width="8" height="7" rx="1.5" />
        <rect x="13" y="4" width="8" height="7" rx="1.5" />
        <rect x="3" y="13" width="8" height="7" rx="1.5" />
        <rect x="13" y="13" width="8" height="7" rx="1.5" />
      </svg>
    )
  }

  if (id === 'employee') {
    return (
      <svg {...common}>
        <rect x="4" y="3" width="16" height="18" rx="2" />
        <circle cx="12" cy="9.5" r="2.4" />
        <path d="M8 17c0-2.2 1.8-3.5 4-3.5s4 1.3 4 3.5" />
      </svg>
    )
  }

  return (
    <svg {...common}>
      <path d="M12 3l7 3v6c0 5-3.5 7.5-7 9-3.5-1.5-7-4-7-9V6l7-3Z" />
      <circle cx="12" cy="10.3" r="2.1" />
      <path d="M9 15c0-1.8 1.3-2.8 3-2.8s3 1 3 2.8" />
    </svg>
  )
}

export function BackendArchitectureHero() {
  const [selected, setSelected] = useState<ApplicationId>('website')
  const [selectedLayerId, setSelectedLayerId] = useState<LayerId>('api')

  const selectedIndex = applications.findIndex((app) => app.id === selected)
  const fanActive = applications.map((_, index) => index === selectedIndex)
  const fanIdlePulse = applications.map(() => false)
  const activeApp = applications[selectedIndex]
  const activeLayer = ALL_LAYERS.find((layer) => layer.id === selectedLayerId)!

  return (
    <SectionWrapper
      as="section"
      className="relative overflow-hidden border-b border-line bg-canvas py-[var(--space-section)]"
      id="backend-is-the-platform"
    >
      <div
        aria-hidden="true"
        className="pointer-events-none absolute top-[5%] right-[-10rem] size-[40rem] rounded-full blur-[80px]"
        style={{
          background:
            'conic-gradient(from 210deg, rgba(67, 111, 225, 0.2), rgba(137, 92, 230, 0.22), rgba(235, 111, 179, 0.15), rgba(67, 111, 225, 0.05))',
        }}
      />

      <motion.div
        animate="visible"
        className="relative"
        initial="hidden"
        variants={revealItem}
        viewport={{ once: true, amount: 0.3 }}
        whileInView="visible"
      >
        <Headline as="h1" eyebrow="ENGINEERING" size="display">
          Enterprise <span className="gradient-text">Backend Architecture</span>
        </Headline>

        <p className="mt-6 max-w-3xl text-body-lg text-pretty text-muted" style={{ lineHeight: 1.8 }}>
          Designing the operational core of a business platform—from domain modelling and
          database architecture to APIs, workflows, and business rules.
        </p>

        <div className="mt-10 max-w-[720px] space-y-5 text-base leading-relaxed text-pretty text-ink sm:text-lg">
          <p>
            Every application is only an interface. The backend is where business rules,
            workflows, permissions, and operational data are managed. It acts as the
            authoritative core of the platform, ensuring that every user works from the same
            operational reality.
          </p>
          <p>
            Whether a booking is created through the website, assigned in the management
            workspace, or completed in the employee app, the backend coordinates every decision
            through one shared system.
          </p>
        </div>
      </motion.div>

      <motion.div
        animate="visible"
        className="mt-14 grid gap-8 lg:grid-cols-[1.35fr_1fr] lg:items-start sm:mt-16"
        initial="hidden"
        variants={revealItem}
        viewport={{ once: true, amount: 0.2 }}
        whileInView="visible"
      >
        <div className="rounded-panel border border-line bg-surface p-5 shadow-card sm:p-8">
          <h2 className="sr-only">Interactive backend architecture diagram</h2>

          <div
            aria-label="Choose an application interface"
            className="grid grid-cols-2 gap-2.5 sm:grid-cols-4 sm:gap-3"
            role="group"
          >
            {applications.map((app, index) => (
              <ApplicationNode
                icon={<AppIcon id={app.icon} />}
                isActive={index === selectedIndex}
                key={app.id}
                label={app.label}
                onSelect={() => setSelected(app.id)}
              />
            ))}
          </div>

          <ConnectorFan activeFlags={fanActive} pulsingFlags={fanIdlePulse} />

          <div className="flex gap-3">
            <div className="flex w-24 shrink-0 flex-col rounded-card border border-dashed border-accent/40 bg-accent-soft/30 p-2">
              <p className="text-center font-mono text-[0.5rem] leading-tight font-semibold tracking-[0.04em] text-accent/80 uppercase">
                Cross-Cutting Concerns
              </p>
              <div className="mt-2 flex flex-1 flex-col justify-between gap-2">
                {CROSS_CUTTING_CONCERNS.map((concern) => (
                  <div className="rounded-full bg-white/70 px-2 py-1.5 text-center" key={concern}>
                    <span className="font-mono text-[0.55rem] leading-tight font-medium tracking-[0.02em] text-accent uppercase">
                      {concern}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            <div className="flex flex-1 flex-col gap-2.5">
              {RIBBONED_LAYERS.map((layer, index) => (
                <div key={layer.id}>
                  <button
                    aria-pressed={layer.id === selectedLayerId}
                    className={`focus-ring w-full rounded-card border bg-surface px-4 py-3 text-left shadow-control transition-colors duration-300 ${
                      layer.id === selectedLayerId ? 'border-accent' : 'border-line hover:border-line-strong'
                    }`}
                    onClick={() => setSelectedLayerId(layer.id)}
                    type="button"
                  >
                    <p className="text-sm font-semibold text-ink">{layer.label}</p>
                    <p className="mt-0.5 font-mono text-xs text-muted">{layer.detail}</p>
                  </button>
                  {index < RIBBONED_LAYERS.length - 1 ? (
                    <div aria-hidden="true" className="flex justify-center text-line-strong">
                      ↓
                    </div>
                  ) : null}
                </div>
              ))}
            </div>
          </div>

          <Connector active height={26} isPulsing={false} />

          <button
            aria-pressed={DATABASE_LAYER.id === selectedLayerId}
            className={`focus-ring w-full rounded-card border bg-surface px-4 py-3 text-left shadow-control transition-colors duration-300 ${
              DATABASE_LAYER.id === selectedLayerId ? 'border-accent' : 'border-line hover:border-line-strong'
            }`}
            onClick={() => setSelectedLayerId(DATABASE_LAYER.id)}
            type="button"
          >
            <p className="text-sm font-semibold text-ink">{DATABASE_LAYER.label}</p>
            <p className="mt-0.5 font-mono text-xs text-muted">{DATABASE_LAYER.detail}</p>
          </button>
        </div>

        <div className="flex flex-col gap-6 lg:sticky lg:top-28">
          <ArchitectureExplanation
            description={activeApp.description}
            eyebrow="Selected interface"
            title={activeApp.label}
          />
          <ArchitectureExplanation
            description={activeLayer.explanation}
            eyebrow="Selected layer"
            title={activeLayer.label}
          />
        </div>
      </motion.div>
    </SectionWrapper>
  )
}
